### ISSUE TITLE
Rancher2

### ISSUE THREAD

**Issue by Napsty** [sshipway/check_rancher#4]
Thanks for this plugin, I'm currently testing it on Rancher 1.x.
Is there any plan to create a compatibility with Rancher 2.x or a separate plugin? 
In Rancher 2, the API uses /v3 endpoint and due to the switch to Kubernetes, the names in the API have changed, too.

**Comment by sshipway** [comment]
I've only used this on a Rancher 1.x system; I'm no longer working at the place I was when I developed this, and as a result no longer have a docker farm to manage - so I've not any current plans to add support for Rancher 2.x.  I would, however, be interested in any pull requests adding this functionality?

**Comment by Napsty** [comment]
Hi Steve, 
Thanks for the response. As time was pressing here at work, I've already started https://github.com/Napsty/check_rancher2 last week because the API v3 is quite different and due to Kubernetes in the background the names have changed (clusters, projects, namespaces, workloads). It's written in Bash though, not Perl as yours. So when the plugin is ready, feel free to translate it to Perl if you like.

**Comment by Napsty** [comment]
Oh - fyi, we still use Rancher 1.x in parallel so if I come across issues in check_rancher I'll let you know if that's ok ;-)
